### ISSUE TITLE
Remove .env.example

### ISSUE THREAD

**Issue by umairwaheed** [prixite/prixite.github.io#52]
We already have env.sample in the repo.

**Comment by rkoalsi** [comment]
I would like to take up this issue

**Comment by umairwaheed** [comment]
@rkoalsi, sure. Please go ahead.

**Comment by rkoalsi** [comment]
I have made the changes and am trying to push the code but I am getting an error that I do not have permission to push to the repository.

**Comment by umairwaheed** [comment]
@rkoalsi please read https://github.com/prixite/prixite.github.io/blob/master/CONTRIBUTING.md on how to contribute.

**Comment by rkoalsi** [comment]
I didn't see that, I went through it and have raised a PR

**Comment by umairwaheed** [comment]
Fixed via #54
