### ISSUE TITLE
DRY: Move Head to Header component

### ISSUE THREAD

**Issue by umairwaheed** [prixite/prixite.github.io#53]
I think we can move the following block to [Header](https://github.com/prixite/prixite.github.io/blob/master/components/header/Header.js) component.

```
      <Head>
        <title>{title}</title>
        <meta name="prixite" content="Prixte" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
```

**Comment by rkoalsi** [comment]
I would like to fix this issue

**Comment by umairwaheed** [comment]
Sure. Please go ahead.

**Comment by rkoalsi** [comment]
Have made the changes and removed the repeated imports and code. Please go through the PR and let me know if there is anything I missed out. Thank you for the opportunity to contribute to your awesome project.

**Comment by umairwaheed** [comment]
Merged via https://github.com/prixite/prixite.github.io/pull/55
